# This workflow is triggered on pushes to the repository.

name: Build Mod with Gradle

on:
  push:
    branches: [ 1.12.2 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_API_KEY: ${{ secrets.GPR_TOKEN }}
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew setupCIWorkspace
          ./gradlew build
#          ./gradlew build publish
